; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit ICM20X@^2.0.7
	esp32async/ESPAsyncWebServer@^3.8.1
	hideakitai/ArduinoEigen@^0.3.2
monitor_rts = 0
monitor_dtr = 0
board_build.partitions = min_spiffs.csv
platform_packages = toolchain-xtensa-esp-elf@14.2.0+20241119
